/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 26-nov-2019 00:10:00 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [dbo].[arquivo]
(
	[id] int NOT NULL,
	[cod_pessoa] int,
	[nomearquivo] nvarchar(300),
	[extencao] nvarchar(5),
	[tamanho] nvarchar(70),
	[dados] varbinary(max),
	[data] nvarchar(10)
)
GO

CREATE TABLE [dbo].[cidade]
(
	[idcidade] int NOT NULL,
	[nomecidade] nvarchar(150),
	[uf] nchar(2)
)
GO

CREATE TABLE [dbo].[endereco]
(
	[idendereco] int NOT NULL,
	[cod_cidade] int,
	[logadrouro] nvarchar(20),
	[endereco] nvarchar(150),
	[numero] int,
	[complemento] ntext,
	[bairro] nvarchar(90),
	[cep] nvarchar(9)
)
GO

CREATE TABLE [dbo].[pessoa]
(
	[idpessoa] int NOT NULL,
	[cod_endereco] int,
	[nomepessoa] nvarchar(180),
	[idade] int,
	[sexo] nchar(1),
	[tipo] nvarchar(80),
	[usuario] nvarchar(50)
)
GO

CREATE TABLE [dbo].[usuario]
(
	[idusuario] int NOT NULL,
	[nomeusuario] nvarchar(180),
	[login] nvarchar(150),
	[senha] nvarchar(150),
	[tipo] nvarchar(90),
	[data] nchar(10)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[arquivo] 
 ADD CONSTRAINT [arquivo_pkey]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [dbo].[cidade] 
 ADD CONSTRAINT [cidade_pkey]
	PRIMARY KEY CLUSTERED ([idcidade] ASC)
GO

ALTER TABLE [dbo].[endereco] 
 ADD CONSTRAINT [endereco_pkey]
	PRIMARY KEY CLUSTERED ([idendereco] ASC)
GO

ALTER TABLE [dbo].[pessoa] 
 ADD CONSTRAINT [pessoa_pkey]
	PRIMARY KEY CLUSTERED ([idpessoa] ASC)
GO

ALTER TABLE [dbo].[usuario] 
 ADD CONSTRAINT [usuario_pkey]
	PRIMARY KEY CLUSTERED ([idusuario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [dbo].[arquivo] ADD CONSTRAINT [fk_arquivo_pessoa]
	FOREIGN KEY ([cod_pessoa]) REFERENCES [dbo].[pessoa] ([idpessoa]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[endereco] ADD CONSTRAINT [fk_endereco_cidade]
	FOREIGN KEY ([cod_cidade]) REFERENCES [dbo].[cidade] ([idcidade]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [dbo].[pessoa] ADD CONSTRAINT [fk_pessoa_endereco]
	FOREIGN KEY ([cod_endereco]) REFERENCES [dbo].[endereco] ([idendereco]) ON DELETE Cascade ON UPDATE Cascade
GO
