--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/12/2022 13:56:36
-- Server version: 8.0.28
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO ebookmvc.produto(id, nome, preco_custo, quantidade_estoque) VALUES
(1, 'Tigela de Vidro', 120.00, 10),
(2, 'Panela de Tramontina Us', 45.00, 10),
(3, 'Pratos', 12.00, 5),
(4, 'Impressora HP', 299.99, 10),
(5, 'Potes de Vidro', 12.00, 80);