--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/12/2022 13:56:36
-- Server version: 8.0.28
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO ebookmvc.usuario(id, login, nome, senha) VALUES
(1, 'warhjr', 'Walter Junior', 'senhah');